FROM node:22

WORKDIR /app

RUN apt-get update && apt-get install -y curl

COPY package.json package-lock.json ./

RUN npm install

COPY . .

RUN npm run build -- --configuration production

RUN npm install -g http-server

WORKDIR /app/dist/angular-frontend

EXPOSE 80

CMD ["http-server", "-p", "80", "-c-1"]
